version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: doc/conf.py

python:
  extra_requirements:
    - documents
  install:
    - requirements: requirements.txt

formats:
    - epub
    - pdf
