# Build PDF & ePub
formats:
    - epub
    - pdf
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: doc/conf.py
  formats:
    - pdf
    - epub

python:
  install:
   - requirements: requirements.txt
